.circleci/config.yml
DiffFormatter.xcodeproj/project.pbxproj
Makefile
Scripts/carthage-verify
fastlane/Fastfile.swift

- Adds verify carthage script/phase
- Links DiffFormatter as test target dependency
- Adds code coverage to scan

Verify carthage

---

DiffFormatter.xcodeproj/project.pbxproj
DiffFormatter/Models/Routing/Argument.swift
DiffFormatter/Routing/ArgumentHandlers/DiffHandler.swift
DiffFormatter/Routing/ArgumentRouter.swift
DiffFormatter/Routing/RoutingContext.swift
DiffFormatter/Utilities/Utilities_Git.swift
DiffFormatter/Utilities/Utilities_Log.swift
DiffFormatterTests/RoutingTests.swift
DiffFormatterTests/__Snapshots__/RoutingTests/testDiffHandler.1.txt

- Auto fetch before performing manual diff
- Add --no-fetch option
- Add basic logging

Add auto-fetch before diff

---

DiffFormatter/Configuration/Configurator.swift
DiffFormatter/Routing/ArgumentHandlers/DiffHandler.swift
DiffFormatter/Utilities/Utilities_Log.swift
DiffFormatter/main.swift

- Add error logging
- Add Logger protocol

[platform] Improve logging

---

DiffFormatter.xcodeproj/project.pbxproj
DiffFormatter/Configuration/Configuration.swift
DiffFormatter/Routing/ArgumentHandlers/DiffHandler.swift
DiffFormatter/Utilities/Utilities_OutputGenerator.swift
DiffFormatterTests/Config/build_number_command_config.json
DiffFormatterTests/Mocks/Mocks.swift
DiffFormatterTests/RoutingTests.swift
DiffFormatterTests/__Snapshots__/ConfigurationTests/testConfigurator.1.txt
DiffFormatterTests/__Snapshots__/RoutingTests/testDiffHandlerBuildNumberCommand.1.txt

- Add support for passing command through config for build number
- Add ability for custom header (similar to existing custom footer)

[feature] More flexible build number support; custom header

---

DiffFormatter/App/Info.plist

Increment build number for release

[version] increment buildnumber

---

DiffFormatter/Configuration/Configuration.swift
DiffFormatter/Routing/ArgumentHandlers/DiffHandler.swift
DiffFormatter/Utilities/Utilities_Shell.swift
DiffFormatterTests/Config/build_number_command_config.json
DiffFormatterTests/__Snapshots__/ConfigurationTests/testConfigurator.1.txt
DiffFormatterTests/__Snapshots__/RoutingTests/testDiffHandlerBuildNumberCommand.1.txt

- Pass NEW_VERSION env var to build number command
- Use array for build num command config to ease parsing

[feature][bugfix] Improve/fix build num command handling

---

DiffFormatter/Models/Routing/ArgumentScheme.swift
DiffFormatter/Routing/ArgumentHandlers/DiffHandler.swift
DiffFormatter/Routing/ArgumentRouter.swift
DiffFormatterTests/Mocks/Mocks.swift
DiffFormatterTests/RoutingTests.swift

Prevent false optional version strings by moving to enum for ArgumentScheme

[platform] ArgumentScheme struct -> enum

---

DiffFormatter.xcodeproj/project.pbxproj
DiffFormatter/Configuration/Configuration.swift
DiffFormatter/Models/Section/Line/Line.swift
DiffFormatter/Models/Section/Line/Line_Components.swift
DiffFormatter/Models/Section/Line/Line_FormatTemplate.swift
DiffFormatter/Models/Section/Section_Info.swift
DiffFormatterTests/__Snapshots__/ConfigurationTests/testConfigurator.1.txt

Introduces the ability to pass a custom default format template via a top-level configuration key

[feature] Configurable default format template

---

Sources/DiffFormatterApp/Output/OutputGenerator.swift
Tests/DiffFormatterAppTests/__Snapshots__/RoutingTests/testDiffHandler.1.txt
Tests/DiffFormatterAppTests/__Snapshots__/RoutingTests/testDiffHandlerBuildNumberCommand.1.txt

[improvement] Filter out empty sections

---

Makefile

- Fixed issue with argument ordering for commit
- Fixed issue with possible existing release branch

[bug fix] Small tweaks/fixes for publish target

---

.circleci/config.yml

Fixes argument order & adds release name

[bug fix][platform] Fix upload release command

---

.circleci/config.yml

Removes ci filter for tags for both `test` and `lint` jobs

[platform] ci tag test filter

---

.circleci/config.yml

- Upgrade to CircleCI config 2.1
- Create and use reusable executor

[ci] Reusable executor

---

Sources/Finch/main.swift
Sources/FinchApp/AppRunner.swift
Sources/FinchApp/Command-Routing/CommandRegistry.swift
Sources/FinchApp/Command-Routing/Commands/Compare/CompareCommand.swift
Sources/FinchApp/Command-Routing/Commands/Compare/VersionsResolver.swift
Sources/FinchApp/Command-Routing/Commands/Config/ConfigCommand.swift
Sources/FinchApp/Services/ChangeLogInfoService.swift
Sources/FinchApp/Strings.swift
Sources/FinchUtilities/Executable.swift
Sources/FinchUtilities/Shell.swift
Sources/FinchUtilities/Strings.swift
Tests/FinchAppTests/AppRunnerTests.swift

- Centralize strings to Strings files
- Remove localization for now

[platform] Relocate strings to Strings files

---

README.md

Adds shields for top level repo info

[docs] Add shields to README

---

README.md

Add small bit of documentation indicating the addition of the `--config` argument

[docs] Update readme to account for --config addition

---

Gemfile
Gemfile.lock

- Add xcpretty to Gemfile
- Update several gems

[platform] Add xcpretty to Gemfile; update gems

---

Package.swift

[platform] Don't force ssh on consumers of Package

---

.circleci/config.yml

[platform][lint] Move lint step to a docker container

---

Package.resolved

[platform] Remove testing dep from resolved

---

.github/workflows/lint.yml
.github/workflows/release.yml

- Fix caching
- Make releases non-draft

[platform] Ci improvements
